GET http://localhost:8089/test
#Accept: aaplication/json

> {%
client.test("test_Hello",function() {
  client.log("测试/test.hello接口");
  client.log(response.body);
  client.log(JSON.stringify(response.body));
  client.assert(response.status === 200, "返回码不是200");
  client.assert(response.body === "Hello World!","结果验证失败");
});
%}

###


POST http://localhost:8089/test/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###还不能够在参数和=之间加空格，坑

GET http://localhost:8089/redis/set/123/test
Accept: application/json

###

POST http://localhost:8089/redis/get/123
Accept: application/json

###
DELETE https://localhost:8089/redis/delete/123
Accept: application/json